#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-ironicclient
Version  : 1.0.0
Release  : 20
URL      : http://tarballs.openstack.org/python-ironicclient/python-ironicclient-1.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-ironicclient/python-ironicclient-1.0.0.tar.gz
Summary  : OpenStack Bare Metal Provisioning API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-ironicclient-bin
Requires: python-ironicclient-python
BuildRequires : Babel
BuildRequires : Jinja2-python
BuildRequires : Pygments
BuildRequires : Sphinx
BuildRequires : anyjson
BuildRequires : appdirs-python
BuildRequires : cliff-python
BuildRequires : coverage-python
BuildRequires : debtcollector-python
BuildRequires : discover-python
BuildRequires : docutils-python
BuildRequires : dogpile.cache-python
BuildRequires : dogpile.core-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : fixtures-python
BuildRequires : flake8-python
BuildRequires : funcsigs-python
BuildRequires : hacking
BuildRequires : hacking-python
BuildRequires : httplib2
BuildRequires : httpretty
BuildRequires : iso8601
BuildRequires : keystoneauth1-python
BuildRequires : linecache2-python
BuildRequires : lxml
BuildRequires : markupsafe-python
BuildRequires : mccabe-python
BuildRequires : monotonic-python
BuildRequires : msgpack-python
BuildRequires : netaddr
BuildRequires : netifaces
BuildRequires : oslo.config
BuildRequires : oslo.i18n
BuildRequires : oslo.serialization
BuildRequires : oslo.utils
BuildRequires : oslosphinx
BuildRequires : oslotest-python
BuildRequires : pbr
BuildRequires : pep8-python
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyflakes-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-keystoneclient
BuildRequires : python-mimeparse-python
BuildRequires : python-mock
BuildRequires : python-openstackclient
BuildRequires : python-subunit
BuildRequires : python3-dev
BuildRequires : pytz
BuildRequires : requests
BuildRequires : setuptools
BuildRequires : six
BuildRequires : stevedore
BuildRequires : testrepository
BuildRequires : testtools-python
BuildRequires : tox
BuildRequires : traceback2-python
BuildRequires : unittest2-python
BuildRequires : virtualenv
BuildRequires : wrapt-python

%description
Python bindings for the Ironic API
==================================
This is a client for the OpenStack `Ironic
<https://wiki.openstack.org/wiki/Ironic>`_ API. It provides a Python API (the
``ironicclient`` module) and a command-line interface (``ironic``).

%package bin
Summary: bin components for the python-ironicclient package.
Group: Binaries

%description bin
bin components for the python-ironicclient package.


%package python
Summary: python components for the python-ironicclient package.
Group: Default
Requires: appdirs-python
Requires: cliff-python
Requires: dogpile.cache-python
Requires: httplib2
Requires: prettytable

%description python
python components for the python-ironicclient package.


%prep
%setup -q -n python-ironicclient-1.0.0

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ironic

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
