#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-ironicclient
Version  : 1.7.0
Release  : 30
URL      : http://tarballs.openstack.org/python-ironicclient/python-ironicclient-1.7.0.tar.gz
Source0  : http://tarballs.openstack.org/python-ironicclient/python-ironicclient-1.7.0.tar.gz
Summary  : OpenStack Bare Metal Provisioning API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-ironicclient-bin
Requires: python-ironicclient-python
BuildRequires : appdirs-python
BuildRequires : cliff-python
BuildRequires : cmd2-python
BuildRequires : dogpile.cache-python
BuildRequires : extras
BuildRequires : extras-python
BuildRequires : jsonpatch-python
BuildRequires : jsonpointer-python
BuildRequires : jsonschema-python
BuildRequires : keystoneauth1-python
BuildRequires : msgpack-python-python
BuildRequires : openstacksdk-python
BuildRequires : os-client-config-python
BuildRequires : os-testr-python
BuildRequires : oslo.utils-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : prettytable
BuildRequires : py-python
BuildRequires : pyparsing-python
BuildRequires : pytest
BuildRequires : python-cinderclient-python
BuildRequires : python-dev
BuildRequires : python-glanceclient-python
BuildRequires : python-novaclient-python
BuildRequires : python-openstackclient-python
BuildRequires : python3-dev
BuildRequires : requests-python
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : tox
BuildRequires : virtualenv

%description
Python bindings for the Ironic API
==================================
This is a client for the OpenStack `Ironic
<https://wiki.openstack.org/wiki/Ironic>`_ API. It provides a Python API (the
``ironicclient`` module) and a command-line interface (``ironic``).

%package bin
Summary: bin components for the python-ironicclient package.
Group: Binaries

%description bin
bin components for the python-ironicclient package.


%package python
Summary: python components for the python-ironicclient package.
Group: Default
Requires: appdirs-python
Requires: dogpile.cache-python
Requires: jsonschema-python
Requires: keystoneauth1-python
Requires: oslo.utils-python
Requires: prettytable
Requires: python-openstackclient-python
Requires: requests-python
Requires: six-python

%description python
python components for the python-ironicclient package.


%prep
%setup -q -n python-ironicclient-1.7.0

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ironic

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
